// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSyncFolder() {
  return window['go']['main']['App']['AddSyncFolder']();
}

export function CancelUpload(arg1) {
  return window['go']['main']['App']['CancelUpload'](arg1);
}

export function CancelUploads() {
  return window['go']['main']['App']['CancelUploads']();
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function DownloadFolder(arg1) {
  return window['go']['main']['App']['DownloadFolder'](arg1);
}

export function GetFeatures() {
  return window['go']['main']['App']['GetFeatures']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Me() {
  return window['go']['main']['App']['Me']();
}

export function OpenWebApp() {
  return window['go']['main']['App']['OpenWebApp']();
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PickFolderForUpload(arg1) {
  return window['go']['main']['App']['PickFolderForUpload'](arg1);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function RecomputeUsage() {
  return window['go']['main']['App']['RecomputeUsage']();
}

export function RemoveSyncFolder(arg1) {
  return window['go']['main']['App']['RemoveSyncFolder'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetBandwidthLimits(arg1, arg2) {
  return window['go']['main']['App']['SetBandwidthLimits'](arg1, arg2);
}

export function SetFolderDirections(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFolderDirections'](arg1, arg2, arg3);
}

export function SetFolderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetFolderEnabled'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SyncHistory() {
  return window['go']['main']['App']['SyncHistory']();
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}

export function UploadFolderPicked(arg1) {
  return window['go']['main']['App']['UploadFolderPicked'](arg1);
}

export function UploadPicked(arg1) {
  return window['go']['main']['App']['UploadPicked'](arg1);
}
