// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {apiclient} from '../models';
import {main} from '../models';
import {sync} from '../models';

export function AddSyncFolder():Promise<settings.SyncFolder>;

export function CancelUpload(arg1:string):Promise<void>;

export function CancelUploads():Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<string>;

export function DownloadFolder(arg1:string):Promise<string>;

export function GetFeatures():Promise<apiclient.Features>;

export function GetSettings():Promise<settings.Settings>;

export function GetVersion():Promise<string>;

export function ListEnvironments():Promise<Array<string>>;

export function ListFiles():Promise<apiclient.ListResponse>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<apiclient.PublicUser>;

export function Logout():Promise<void>;

export function Me():Promise<apiclient.PublicUser>;

export function OpenWebApp():Promise<void>;

export function PickFile(arg1:string):Promise<main.LocalFile>;

export function PickFolderForUpload(arg1:string):Promise<Array<main.LocalFile>>;

export function PreviewFile(arg1:string):Promise<apiclient.PreviewResult>;

export function RecomputeUsage():Promise<number>;

export function RemoveSyncFolder(arg1:number):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RequestQuit():Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetBandwidthLimits(arg1:number,arg2:number):Promise<void>;

export function SetFolderDirections(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function SetFolderEnabled(arg1:number,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function SyncHistory():Promise<Array<sync.LogEntry>>;

export function SyncStatus():Promise<sync.Status>;

export function UploadFile(arg1:string):Promise<string>;

export function UploadFolderPicked(arg1:Array<string>):Promise<void>;

export function UploadPicked(arg1:string):Promise<void>;
